### ISSUE TITLE
List of uploads with ability to download/upload them

### ISSUE THREAD

**Issue by tsani** [labcoders/playback-client#5]
The list view should show whether a download is locally stored #6 its name #7 and whether it is uploaded. Tapping a recording should open another view with details about the recording (time recorded at, duration, file size, uploaded at (if at all), and provide actions to upload/download the recording)

**Comment by kevin-li-195** [comment]
Some shitty, preliminary, ugly list is done. Making it pretty is another thing entirely.

**Comment by kevin-li-195** [comment]
#16 encompasses this.
